### ISSUE TITLE
Can't see option to merge

### ISSUE THREAD

**Issue by skywinder** [jonathanKingston/merge-windows#9]
Firefox 81.0 (64-bit)
MacOS

I have 2 open windows.
Install extension
Refresh window
open one more window (3rd)
still, can't see option.

![image](https://user-images.githubusercontent.com/3356474/94763369-445fa100-03d4-11eb-89b2-e52df81ac7b6.png)

**Comment by Zegnat** [comment]
It should add context items to the right-click menu on tabs and on the page body. I do not think it is possible to insert items into the little three-dots menu of the address bar.

Where to click seems to be a repeated question … #7 😞

PS: where does that “also forked to” message in your GitHub screenshots originate from? Never seen that before! (And as an aside: I created [that fork](https://github.com/Zegnat/browserext-window-merger) to address a number of open tickets on this repo, if you are having similar issues I would recommend you check it out. `</shameless-plug>`)

**Comment by skywinder** [comment]
@Zegnat so, it meant that looking for this button  in wrong menu? I check toolbar menu, but there is also no extra button.
I can't find it, can you guide me as a dummy, where it's hidden how to open this menu? 🕵️‍♂️
![image](https://user-images.githubusercontent.com/3356474/95283598-65b60680-0886-11eb-851f-c2c53bfa9712.png)

ps:
Check this is plugin for firefox: https://github.com/musically-ut/lovely-forks 👍

**Comment by skywinder** [comment]
@Zegnat  what the difference between your forks? as I can see this one os not updated for the last 3 years, but the firefox plugin referenced to this repo. So which one is preferred to use?

**Comment by skywinder** [comment]
Oh, I see! there is a lot of updates. I even made PR, as a reference.
https://github.com/jonathanKingston/merge-windows/pull/10

It would be nice to notify people about the new updated option. Thanks for metion!

**Comment by Zegnat** [comment]
> so, it meant that looking for this button in wrong menu? I check toolbar menu, but there is also no extra button.
I can't find it, can you guide me as a dummy, where it's hidden how to open this menu? 🕵️‍♂️

@skywinder sorry if it was not clear. I recently received [a review over on AMO](https://addons.mozilla.org/en-GB/firefox/addon/window-merger/reviews/1602333/) that someone could not find the menu on my fork either.

Both this plugin and my fork add the option to the page’s **context menu**. That is generally the menu that comes up when you right click on a page. If you have multiple windows open in Firefox, right clicking anywhere on the page should show the menu option. Both for this plugin and my fork. This is what I see when I right click right next to your screenshot, note the little Merge Windows at the bottom:

![rightclick](https://user-images.githubusercontent.com/490579/95349414-5b642e80-08bf-11eb-9953-285c7e56ad83.png)

If you have any ideas how to make it more clear in the README and on the Add-ons site, feel free to open up an issue or PR to my repo and I will get that merged ASAP.

> what the difference between your forks? as I can see this one os not updated for the last 3 years, but the firefox plugin referenced to this repo. So which one is preferred to use?

I prefer to use my own plugin. But the plugin in this repo also works. They are two completely different works by now. If you do not need the extra options I developed, use this one instead. (Although I personally of course think everyone should use mine, but I might be biased 😉)

**Comment by skywinder** [comment]
done https://github.com/Zegnat/browserext-window-merger/pull/10
